developer-standards:
  CONTRIBUTING.md: "Code guidelines: Naming conventions, file structure, logging standards, and test conventions"
  .editorconfig: "Authoritative code style specification"

work-tracking:
  jira:
    issue-key-pattern: ADR-\d+
    recognize-patterns:
    - Task \d+
    - Epic \d+
    - Jira \d+
    task-work-item:
      type: Task
      replace-description-when: This task is added to a spec, and the current description contains initial notes
      update-description-when: Revising a spec
    feature-work-item:
      type: Epic
      update-description-when: Adding to a spec or revising a spec
      replace-description-when: Writing a spec for the first time, and the description contains initial notes
  github:
    issue-key-pattern: Issue-\d+
    recognize-patterns:
    - '#\d+'
    - Issue \d+
    - GitHub \d+
    bug-item:
      type: Issue

documentation:
  format: MarkDown
  architecture:
    location: In folder with related source files
    name-format: "_doc_<slug>.md"
    search: grep -rl "^Summary:" . --include="_doc_*.md"
  specs:
    location: docs/
    name-format: "_design_<slug>.md"
    search: grep -rl "<work-item-id>" docs/ --include="_design_*.md"
  dev-specs:
    location: In folder with related source files
    name-format: "_spec_<slug>.md"
    search: grep -rl "<work-item-id>" . --include="_spec_*.md"

git-repo:
  working-branches:
    task: dev/<user-alias>/<task-work-item-id>
    feature: feature/<feature-work-item-id>-<slug>
  commit:
    when: A task implementation is complete, or on each individual bug or code review comment addressed
  push:
    enabled: true
    when: Only after a full successful run of scripts/validate-build and scripts/validate-tests
  create-pr:
    enabled: true
    draft: true
    when: the working branch has been pushed and a PR does not already exist
  promote-pr:
    enabled: true
    when: All review comments are addressed and validation passes
