developer-standards:
  CONTRIBUTING.md: "Code guidelines: Naming conventions, file structure, logging standards, and test conventions"
  .editorconfig: "Authoritative code style specification"

work-tracking:
  jira:
    issue-key-pattern: ADR-\d+
    recognize-patterns:
    - Task \d+
    - Epic \d+
    - Jira \d+
    task-work-item:
      type: Task
      replace-description-when: This task is added to a spec, and the current description contains initial notes
      update-description-when: Revising a spec
    feature-work-item:
      type: Epic
      update-description-when: Adding to a spec or revising a spec
      replace-description-when: Writing a spec for the first time, and the description contains initial notes
  github:
    issue-key-pattern: Issue-\d+
    recognize-patterns:
    - '#\d+'
    - Issue \d+
    - GitHub \d+
    bug-item:
      type: Issue

documentation:
  format: MarkDown
  architecture:
    location: In folder with related source files
    name-format: "_doc_<slug>.md"
    search: grep -rl "^Summary:" . --include="_doc_*.md"
  specs:
    location: docs/
    name-format: "_design_<slug>.md"
    search: grep -rl "<work-item-id>" docs/ --include="_design_*.md"
  dev-specs:
    location: In folder with related source files
    name-format: "_spec_<slug>.md"
    search: grep -rl "<work-item-id>" . --include="_spec_*.md"

validation:
  - scripts/validate-build.sh
  - scripts/validate-tests.sh

git-repo:
  working-branches:
    task: dev/<user-alias>/<task-work-item-id>
    feature: feature/<feature-work-item-id>-<slug>

instructions:
  after-signoff-success:
    request-review: Request a GitHub review from jodavis
    assign-work-item: Assign work item to jodasoft@outlook.com
